version: '2'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - '8031:80'
    depends_on:
      - php
    volumes:
      - ./www:/opt/work
    container_name: site_phppa_nginx
  php:
    build: ./docker/php
    volumes:
      - ./www:/opt/work
    environment:
      XDEBUG_HOST: 192.168.0.104 # CHANGE TO YOUR LOCAL IP ADDRESS!!!
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
    container_name: site_phppa_php
